"""
Repair script: restores the corrupted generate_meal_plan section.
Run from the nutriai-backend directory: python fix_mealplan.py
"""

with open("main.py", "rb") as f:
    content = f.read()

BROKEN_START = b'@app.get("/api/conditions/{slug}")\r\r\ndef save_meal_plan'
BROKEN_END   = b'@app.get("/api/mealplan/history")'

si = content.find(BROKEN_START)
ei = content.find(BROKEN_END)
print(f"si={si}, ei={ei}")

if si < 0 or ei <= si:
    print("ERROR: markers not found. Dumping context around slug route...")
    idx = content.find(b"/api/conditions/{slug}")
    if idx >= 0:
        print(repr(content[max(0,idx-50):idx+300]))
    raise SystemExit(1)

# ── Replacement block ──────────────────────────────────────────────────────────
R = b"\r\r\n"  # line ending used in the file

lines = [
    b'@app.get("/api/conditions/{slug}")',
    b'def get_condition_detail(slug: str):',
    b'    """Get full detail for a specific condition by slug."""',
    b'    for c in _CONDITIONS_DB:',
    b'        if c["slug"] == slug:',
    b'            return c',
    b'    raise HTTPException(status_code=404, detail=f"Condition \'{slug}\' not found in encyclopedia")',
    b'',
    b'@app.post("/api/nutrition/calculate")',
    b'def calculate_nutrition(ingredient_amounts: dict):',
    b'    """',
    b'    Calculate nutrition for a list of ingredients with amounts.',
    b'    Body: {"oats": 100, "banana": 50, "almond milk unsweetened": 200}',
    b'    """',
    b'    total = {"calories": 0, "protein": 0, "carbs": 0, "fat": 0, "fiber": 0, "sodium": 0}',
    b'    breakdown = {}',
    b'',
    b'    for ingredient, grams in ingredient_amounts.items():',
    b'        key = ingredient.lower()',
    b'        data = NUTRITION["ingredients"].get(key)',
    b'        if data:',
    b'            factor = grams / 100',
    b'            breakdown[ingredient] = {',
    b'                "grams":    grams,',
    b'                "calories": round(data["calories_kcal"] * factor, 1),',
    b'                "protein":  round(data["protein_g"]    * factor, 1),',
    b'                "carbs":    round(data["carbs_g"]      * factor, 1),',
    b'                "fat":      round(data["fat_g"]        * factor, 1),',
    b'                "fiber":    round(data["fiber_g"]      * factor, 1),',
    b'            }',
    b'            total["calories"] += breakdown[ingredient]["calories"]',
    b'            total["protein"]  += breakdown[ingredient]["protein"]',
    b'            total["carbs"]    += breakdown[ingredient]["carbs"]',
    b'            total["fat"]      += breakdown[ingredient]["fat"]',
    b'            total["fiber"]    += breakdown[ingredient]["fiber"]',
    b'',
    b'    return {',
    b'        "total":     {k: round(v, 1) for k, v in total.items()},',
    b'        "breakdown": breakdown',
    b'    }',
    b'',
    b'# -- Meal Plan Endpoints -------------------------------------------------------',
    b'@app.get("/api/mealplan/generate")',
    b'def generate_meal_plan(weeks: int = None, user=Depends(get_current_user)):',
    b'    """',
    b'    Auto-calculates how many weeks to generate based on the users compliant',
    b'    recipe pool. weeks = floor(max_compliant_across_meal_types / 7).',
    b'    Capped at 16 weeks. Every week uses totally unique recipes -- zero repeats.',
    b'    Optional: pass ?weeks=N to override the auto-calculated count (1-16).',
    b'    """',
    b'    MAX_WEEKS = 16',
    b'    MIN_WEEKS = 1',
    b'    requested_weeks = weeks  # None = auto-calculate, int = user override',
    b'',
    b'    def _calc_daily_calorie_target():',
    b'        weight = user.get("weight", 70) or 70',
    b'        height = user.get("height", 1.70) or 1.70',
    b'        age    = user.get("age", 30) or 30',
    b'        gender = (user.get("gender") or "male").lower()',
    b'        goal   = user.get("goal") or "Maintenance"',
    b'        if gender == "male":',
    b'            bmr = 10 * weight + 6.25 * (height * 100) - 5 * age + 5',
    b'        else:',
    b'            bmr = 10 * weight + 6.25 * (height * 100) - 5 * age - 161',
    b'        if goal == "Weight Loss":   return int(bmr * 1.3 - 300)',
    b'        elif goal == "Muscle Gain": return int(bmr * 1.5 + 300)',
    b'        else:                       return int(bmr * 1.4)',
    b'',
    b'    daily_cal = _calc_daily_calorie_target()',
    b'',
    b'    meal_cal_targets = {',
    b'        "Breakfast": daily_cal * 0.25,',
    b'        "Lunch":     daily_cal * 0.35,',
    b'        "Dinner":    daily_cal * 0.30,',
    b'        "Snack":     daily_cal * 0.10,',
    b'    }',
    b'',
    b'    b_filtered = filter_recipes_for_user(user, "Breakfast")',
    b'    l_filtered = filter_recipes_for_user(user, "Lunch")',
    b'    d_filtered = filter_recipes_for_user(user, "Dinner")',
    b'    s_filtered = filter_recipes_for_user(user, "Snack")',
    b'',
    b'    b_compliant = [r for r in b_filtered if r.get("is_compliant", True)]',
    b'    l_compliant = [r for r in l_filtered if r.get("is_compliant", True)]',
    b'    d_compliant = [r for r in d_filtered if r.get("is_compliant", True)]',
    b'    s_compliant = [r for r in s_filtered if r.get("is_compliant", True)]',
    b'',
    b'    pool_sizes = {',
    b'        "Breakfast": len(b_compliant),',
    b'        "Lunch":     len(l_compliant),',
    b'        "Dinner":    len(d_compliant),',
    b'        "Snack":     len(s_compliant),',
    b'    }',
    b'',
    b'    max_pool   = max(pool_sizes.values()) if any(pool_sizes.values()) else 7',
    b'    auto_weeks = max(MIN_WEEKS, min(MAX_WEEKS, max_pool // 7))',
    b'    if auto_weeks < MIN_WEEKS:',
    b'        auto_weeks = MIN_WEEKS',
    b'',
    b'    # If user explicitly requested a custom number of weeks, honour it',
    b'    if requested_weeks is not None:',
    b'        auto_weeks = max(MIN_WEEKS, min(MAX_WEEKS, requested_weeks))',
    b'',
    b'    total_days = auto_weeks * 7',
    b'',
    b'    def _build_pool(compliant, filtered, needed, cal_target):',
    b'        def cal_of(r):',
    b'            return (r.get("nutrition_per_serving") or {}).get("calories", 0) or 0',
    b'        BAND   = max(50, cal_target * 0.15)',
    b'        within = [r for r in compliant if abs(cal_of(r) - cal_target) <= BAND]',
    b'        over   = sorted([r for r in compliant if cal_of(r) - cal_target > BAND],',
    b'                        key=lambda r: cal_of(r) - cal_target)',
    b'        under  = sorted([r for r in compliant if cal_target - cal_of(r) > BAND],',
    b'                        key=lambda r: cal_target - cal_of(r))',
    b'        _random.shuffle(within)',
    b'        full_pool = within + over + under',
    b'        if not full_pool:',
    b'            return []',
    b'        if len(full_pool) < needed:',
    b'            nc = sorted([r for r in filtered if not r.get("is_compliant", True)],',
    b'                        key=lambda r: abs(cal_of(r) - cal_target))',
    b'            full_pool = full_pool + nc',
    b'        result = list(full_pool)',
    b'        while len(result) < needed:',
    b'            chunk = full_pool.copy()',
    b'            _random.shuffle(chunk)',
    b'            result.extend(chunk)',
    b'        return result[:needed]',
    b'',
    b'    all_breakfasts = _build_pool(b_compliant, b_filtered, total_days, meal_cal_targets["Breakfast"])',
    b'    all_lunches    = _build_pool(l_compliant, l_filtered, total_days, meal_cal_targets["Lunch"])',
    b'    all_dinners    = _build_pool(d_compliant, d_filtered, total_days, meal_cal_targets["Dinner"])',
    b'    all_snacks     = _build_pool(s_compliant, s_filtered, total_days, meal_cal_targets["Snack"])',
    b'',
    b'    day_names = ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"]',
    b'    all_days  = []',
    b'',
    b'    for idx in range(total_days):',
    b'        b = all_breakfasts[idx] if idx < len(all_breakfasts) else None',
    b'        l = all_lunches[idx]    if idx < len(all_lunches)    else None',
    b'        d = all_dinners[idx]    if idx < len(all_dinners)    else None',
    b'        s = all_snacks[idx]     if idx < len(all_snacks)     else None',
    b'        total_cal = sum(m["nutrition_per_serving"]["calories"] for m in [b, l, d, s] if m)',
    b'        all_days.append({',
    b'            "day":            day_names[idx % 7],',
    b'            "week":           (idx // 7) + 1,',
    b'            "day_index":      idx,',
    b'            "breakfast":      b,',
    b'            "lunch":          l,',
    b'            "dinner":         d,',
    b'            "snack":          s,',
    b'            "total_calories": round(total_cal, 1)',
    b'        })',
    b'',
    b'    plan_weeks = []',
    b'    for w in range(1, auto_weeks + 1):',
    b'        week_days = [d for d in all_days if d["week"] == w]',
    b'        week_cal  = sum(d["total_calories"] for d in week_days)',
    b'        plan_weeks.append({',
    b'            "week":               w,',
    b'            "label":              f"Week {w}",',
    b'            "days":               week_days,',
    b'            "avg_daily_calories": round(week_cal / len(week_days), 1) if week_days else 0,',
    b'        })',
    b'',
    b'    avg_calories  = round(sum(d["total_calories"] for d in all_days) / len(all_days), 1) if all_days else 0',
    b'    total_protein = sum(',
    b'        sum((m["nutrition_per_serving"].get("protein", 0) or 0)',
    b'            for m in [d["breakfast"], d["lunch"], d["dinner"], d["snack"]] if m)',
    b'        for d in all_days',
    b'    )',
    b'    avg_protein    = round(total_protein / len(all_days), 1) if all_days else 0',
    b'    compliant_days = sum(',
    b'        1 for d in all_days',
    b'        if all(',
    b'            m.get("is_compliant", True)',
    b'            for m in [d["breakfast"], d["lunch"], d["dinner"], d["snack"]] if m',
    b'        )',
    b'    )',
    b'',
    b'    return {',
    b'        "success":     True,',
    b'        "plan_type":   "dataset",',
    b'        "total_weeks": auto_weeks,',
    b'        "total_days":  total_days,',
    b'        "weeks":       plan_weeks,',
    b'        "days":        all_days,',
    b'        "pool_stats": {',
    b'            "safe_breakfasts":      pool_sizes["Breakfast"],',
    b'            "safe_lunches":         pool_sizes["Lunch"],',
    b'            "safe_dinners":         pool_sizes["Dinner"],',
    b'            "safe_snacks":          pool_sizes["Snack"],',
    b'            "largest_pool":         max_pool,',
    b'            "generated_weeks":      auto_weeks,',
    b'            "daily_calorie_target": daily_cal,',
    b'        },',
    b'        "summary": {',
    b'            "avg_daily_calories": avg_calories,',
    b'            "avg_daily_protein":  avg_protein,',
    b'            "total_meals":        total_days * 4,',
    b'            "compliant_days":     compliant_days,',
    b'            "total_days":         total_days,',
    b'        }',
    b'    }',
    b'',
    b'@app.get("/api/mealplan/history")',
]

replacement = R.join(lines)

new_content = content[:si] + replacement + content[ei + len(BROKEN_END):]

with open("main.py", "wb") as f:
    f.write(new_content)

print(f"SUCCESS: replaced {ei - si} bytes. New file size: {len(new_content)} bytes.")
