"""
train_model.py --" NutriAI Condition Safety Model Trainer
========================================================
Trains one Random Forest classifier per health condition using the
synthetic medical-guideline dataset generated by generate_training_data.py.

Run:
    python generate_training_data.py   # first time only
    python train_model.py

Output:
    models/condition_classifier.pkl
"""

import os
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings("ignore")

BASE_DIR   = os.path.dirname(__file__)
DATA_DIR   = os.path.join(BASE_DIR, "data")
MODELS_DIR = os.path.join(BASE_DIR, "models")
MODEL_PATH = os.path.join(MODELS_DIR, "condition_classifier.pkl")

NHANES_CSV    = os.path.join(DATA_DIR, "training_data_nhanes.csv")
SYNTHETIC_CSV = os.path.join(DATA_DIR, "training_data.csv")

# "" Feature columns (must match generate_training_data.py exactly) """""""""""""
FEATURE_COLS = [
    "calories_kcal", "protein_g", "carbs_g", "fat_g", "fiber_g",
    "sugar_g", "sodium_mg", "potassium_mg", "calcium_mg", "iron_mg",
    "vitamin_c_mg", "glycemic_index", "saturated_fat_g",
    "gluten_free", "dairy_free", "purine_level", "fodmap_score", "goitrogen_flag",
]

CONDITIONS = [
    "Diabetes", "Hypertension", "Heart Disease", "Obesity",
    "Celiac Disease", "Lactose Intolerance", "Kidney Disease",
    "High Cholesterol", "PCOS", "Thyroid Disorder",
    "Anemia", "Gout", "IBS", "Liver Disease",
    "GERD", "Osteoporosis", "Rheumatoid Arthritis", "NAFLD",
    "Gallbladder Disease", "Crohn's Disease", "Chronic Pancreatitis", "Migraine",
]


def train():
    os.makedirs(MODELS_DIR, exist_ok=True)

    # -- Load and combine datasets ----------------------------------------------
    dfs = []
    sources = []

    if os.path.exists(NHANES_CSV):
        df_nhanes = pd.read_csv(NHANES_CSV)
        # Drop NHANES-only clinical flag columns (not model features)
        drop_cols = [c for c in df_nhanes.columns if c.startswith("clin_")]
        df_nhanes = df_nhanes.drop(columns=drop_cols, errors="ignore")
        dfs.append(df_nhanes)
        sources.append(f"NHANES real-world ({len(df_nhanes)} rows)")

    if os.path.exists(SYNTHETIC_CSV):
        dfs.append(pd.read_csv(SYNTHETIC_CSV))
        sources.append(f"Synthetic guideline ({len(dfs[-1])} rows)")

    if not dfs:
        raise FileNotFoundError(
            "No training data found.\n"
            "Run: python nhanes_etl.py    (real-world NHANES data)\n"
            "  or python generate_training_data.py  (synthetic fallback)"
        )

    df = pd.concat(dfs, ignore_index=True)

    print("=" * 60)
    print("  NutriAI -- Condition Safety Model Trainer")
    print("=" * 60)
    print(f"\nData sources combined:")
    for s in sources:
        print(f"  + {s}")

    print(f"  {len(df)} samples  |  {len(FEATURE_COLS)} features  |  {len(CONDITIONS)} conditions\n")

    X = df[FEATURE_COLS].values
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    # -- Train one model per condition ------------------------------------------
    models = {}
    print(f"  {'Condition':<26}  {'F1 (5-fold)':<14}  {'Accuracy':<10}  Safe%")
    print(f"  {'-'*60}")

    for condition in CONDITIONS:
        label_col = f"label_{condition}"
        if label_col not in df.columns:
            print(f"  [{condition:<24}]  SKIPPED - label column missing")

            continue

        y = df[label_col].values

        clf = RandomForestClassifier(
            n_estimators   = 150,
            max_depth      = 12,
            min_samples_leaf = 4,
            class_weight   = "balanced",   # handles class imbalance
            random_state   = 42,
            n_jobs         = -1,
        )

        # Cross-validated F1 and accuracy
        f1_scores  = cross_val_score(clf, X, y, cv=cv, scoring="f1")
        acc_scores = cross_val_score(clf, X, y, cv=cv, scoring="accuracy")

        # Final fit on all data
        clf.fit(X, y)
        models[condition] = clf

        safe_pct = y.mean() * 100
        print(
            f"  {condition:<26}  "
            f"F1={f1_scores.mean():.3f} +/-{f1_scores.std():.3f}  "

            f"Acc={acc_scores.mean():.3f}    "
            f"{safe_pct:.0f}%"
        )

    # "" Feature importance summary """""""""""""""""""""""""""""""""""""""""""""
    print(f"\n  Top 5 most important features (averaged across all models):")
    importances = np.zeros(len(FEATURE_COLS))
    for clf in models.values():
        importances += clf.feature_importances_
    importances /= len(models)
    top5 = np.argsort(importances)[::-1][:5]
    for rank, idx in enumerate(top5, 1):
        print(f"    {rank}. {FEATURE_COLS[idx]:<22}  {importances[idx]:.4f}")

    # "" Save """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    payload = {
        "models":     models,
        "features":   FEATURE_COLS,
        "conditions": CONDITIONS,
        "version":    "2.0",
    }
    joblib.dump(payload, MODEL_PATH, compress=3)

    print(f"\n{'='*60}")
    print(f"  [OK] {len(models)} models saved -> {MODEL_PATH}")
    print(f"  Model size: {os.path.getsize(MODEL_PATH) / 1024:.1f} KB")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    train()
